### PR TITLE
Support the option for 12/24 hour view.

### PR DESCRIPTION
**Pull request by emanfu**
Thanks for providing this plugin. It's really useful! I think it'll be even better if the option for 12/24 hour view option is provided for Android. Please kindly review my changes in the PR. If you think it's useful, please approve and merge it. Thanks!

### CODE REVIEW

**Comment by skwasjer** [comment]
Thanks, it's best to keep 'true' default for compatibility sake, and I'll have to update doc but I'll pull this in for sure soon.

**Comment by emanfu** [comment]
Yes, I agree. I have changed the default value as suggested.

**Comment by macsupport** [comment]
Is there an option to add this in iOS? I've tried setting the locale to "en_GB" to try and force 24 hour but no luck.

**Comment by skwasjer** [comment]
There is no way to configure it other then setting the locale in the plugin config and optionally toggling the flag (if available on your device) under Settings > General > Date & Time > 24-Hour Time.

And you could alternatively also try `en-GB`.

**Comment by macsupport** [comment]
I thought it was`en_GB`. Tried both but no luck. Thanks for the response.

**Pull request merged**
